name: SpawnsMerger
version: '1.2-SNAPSHOT'
main: dev.frosty.spawnsMerger.SpawnsMerger
api-version: '1.21'
depend: [NBTAPI]
commands:
  givespawner:
    description: Gibt dir einen begrenzten Spawner
    usage: /givespawner <MobType> <Anzahl-Spawns>
  mergespawner:
    description: Öffnet ein Menü zum Zusammenführen von Spawnern
    usage: /mergespawner
